### ISSUE TITLE
How to run Scala 3 version of Ammonite?

### ISSUE THREAD

**Issue by myknbani** [coursier/apps#124]
It defaults to Scala 2 and I can't Google for specific instructions on this matter.

**Comment by alexarchambault** [comment]
Things like this work for me:
```text
$ cs launch ammonite --scala 3.0.2
```

**Comment by alexarchambault** [comment]
About making it the default, I'm not sure what's needed for that. Might just be a matter of tweaking how Scala versions are listed somewhere.

**Comment by myknbani** [comment]
@alexarchambault Thanks it works.

```
Welcome to the Ammonite Repl 2.4.1-1-230b38e9 (Scala 3.0.2 Java 16.0.1)
```

It's the version number that I can't seem to get right.

```
> coursier launch ammonite --scala 3.1.0                                   

OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Resolution error: Error downloading com.lihaoyi:ammonite_3.1.0:latest.release
  not found: /home/michael/.ivy2/local/com.lihaoyi/ammonite_3.1.0
  not found: https://repo1.maven.org/maven2/com/lihaoyi/ammonite_3.1.0/maven-metadata.xml
```

Installing Ammonite directly from AUR on Manjaro also produces:

```
Welcome to the Ammonite Repl 2.4.1 (Scala 3.0.2 Java 17.0.1)
```

So I guess `3.0.2` it is :joy_cat:

**Comment by myknbani** [comment]
> About making it the default, I'm not sure what's needed for that. Might just be a matter of tweaking how Scala versions are listed somewhere in the coursier code base.

https://github.com/com-lihaoyi/Ammonite/blob/master/build.sc#L52

Making a wild guess, this is the build script for the Github releases, and we can only use the versions listed here.

**Comment by alexarchambault** [comment]
Indeed, I need to have another look at bumping the Scala 3 version in Ammonite.
