### ISSUE TITLE
Error installing scala-cli

### ISSUE THREAD

**Issue by Miuler** [coursier/apps#163]
Error installing scala-cli

```shell
cs install -v scala-cli

# Using install directory /home/miuler/.local/share/coursier/bin
# Found app scala-cli in channel io.get-coursier:apps
# Error downloading gz+https://github.com/VirtusLab/scala-cli/releases/download/v0.1.10/scala-cli-x86_64-pc-linux.gz
```

**Comment by alexarchambault** [comment]
I'm not sure what the error is, there aren't many details in your report. Please try again with the latest coursier version (`cs update cs` might install it, but better even, re-install [the latest version](https://github.com/coursier/coursier/releases/tag/v2.1.0-M6-49-gff26f8e39) manually), and report back if it still fails.
