### ISSUE TITLE
Scala 3.5 is using the wrong launcher 

### ISSUE THREAD

**Issue by JD557** [coursier/apps#238]
Scala 3.5.0 is using the default `dotty.tools.MainGenericRunner`: https://github.com/coursier/apps/blob/main/apps/resources/scala.json#L2

In turn, the following warning is launched:

```
[warning] MainGenericRunner class is deprecated since Scala 3.5.0, and Scala CLI features will not work.
[warning] Please be sure to update to the Scala CLI launcher to use the new features.
[warning] It appears that your Coursier-based Scala installation is misconfigured.
[warning] To update to the new Scala CLI runner, please update (coursier, cs) commands first before re-installing scala.
[warning] Check the Scala 3.5.0 release notes to troubleshoot your installation.
```

So I think we need to define a `mainClass` override, similar to https://github.com/coursier/apps/blob/main/apps/resources/scala.json#L35

But I don't know what's the new main class 😓

**Comment by SethTisue** [comment]
@bishabosha I think either this might interest you, or you could suggest who else might want to take a look?

**Comment by bjornregnell** [comment]
Well well. Still only a few early adopters have already installed. (But I'm counting the hours until my 200+ students will go ahead and install on all sorts of boxes...)

**Comment by bishabosha** [comment]
@bjornregnell hopefully this shouldn't affect users who install coursier for the first time

**Comment by bjornregnell** [comment]
> @JD557 did you follow the steps before opening the issue?
I have followed all the steps and it only works if you give an explicit `cs install scala:3.5.0` after a clean install.
See further here: https://contributors.scala-lang.org/t/3-5-0-release-thread/6666/66

**Comment by bjornregnell** [comment]
@bishabosha how fast can a new cs version be released if needed? or an updated JSON if that is enough?

**Comment by bishabosha** [comment]
ok, perhaps we can rewrite the scala.json to make the native runner the default, and then version overrides use jvm launcher?

**Comment by bjornregnell** [comment]
that would be great! Do you know what the JSON should say instead?

**Comment by JD557** [comment]
Ok, I edited the title to a more generic one

**Comment by bishabosha** [comment]
@Gedochao please check out my PR https://github.com/coursier/apps/pull/239
